### ISSUE TITLE
file location

### ISSUE THREAD

**Issue by skyburchard** [imgntn/j360#2]
I am struggling to find where the .tar files are stored after a capture has been started and stopped. i'm not sure if this is an issue or i'm simply doing something wrong. i'm running the demo.html file locally on my machine. using chrome on mac, apache server.

**Comment by imgntn** [comment]
Hi, thanks for the patience --

The web browser should prompt you to save the .tar file every so often, according to the autoSaveTime parameter used when creating a capturer.  

```// Create a capturer that exports Equirectangular 360 JPG images in a TAR file
var capturer360 = new CCapture({
    format: 'threesixty',
    display: true,
    autoSaveTime: 3,
});```

Do you not get a popup prompt at all?  Newer versions of Chrome will also ask you to confirm that you want to download multiple files from a site.

Does running the demo past 3 seconds bring up the prompt for you?   https://imgntn.github.io/j360/demo.html

Perhaps the download is being blocked by a plugin or extension.  Try an incognito window.  

Maybe an antivirus is blocking, check if you've got any of that going.  

The first filename  is "j360_part_0000000.tar" if you want to search for it on your hard drives.

Let me know how it goes!

**Comment by imgntn** [comment]
closing this pending a response - hope you've figured it out!
